create table if not exists users (
  id bigint generated by default as identity primary key,
  user_id text unique not null,
  name text,
  created_at timestamptz not null default now(),
  is_active boolean not null default true
);

create table if not exists admins (
  id bigint generated by default as identity primary key,
  email text unique not null,
  password_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists days (
  id bigint generated by default as identity primary key,
  day_number integer unique not null,
  title text not null,
  description text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists questions (
  id bigint generated by default as identity primary key,
  day_id bigint not null references days(id) on delete cascade,
  question_order integer not null,
  question_type text not null check (question_type in ('short_text', 'multiple_response')),
  question_text text not null,
  image_url text,
  correct_answer text,
  expected_word_count integer,
  explanation text,
  created_at timestamptz not null default now()
);

create table if not exists question_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references questions(id) on delete cascade,
  option_text text not null,
  is_correct boolean not null default false
);

create table if not exists attempts (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  question_id bigint not null references questions(id) on delete cascade,
  submitted_answer text,
  selected_options jsonb not null default '[]'::jsonb,
  is_correct boolean not null,
  feedback_data jsonb not null,
  attempt_number integer not null,
  created_at timestamptz not null default now()
);

create table if not exists progress (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  day_id bigint not null references days(id) on delete cascade,
  current_question_id bigint references questions(id) on delete set null,
  completed_question_count integer not null default 0,
  total_question_count integer not null default 0,
  is_day_completed boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (user_id, day_id)
);

create table if not exists participant_day_access (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  day_id bigint not null references days(id) on delete cascade,
  access_code text unique not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, day_id)
);

alter table users enable row level security;
alter table admins enable row level security;
alter table days enable row level security;
alter table questions enable row level security;
alter table question_options enable row level security;
alter table attempts enable row level security;
alter table progress enable row level security;
alter table participant_day_access enable row level security;

insert into admins (email, password_hash)
values ('admin@example.com', 'c158026734a4fc5ddd91a176212e5807:0d60a1f555254705f8f93c13a447c0a0ff197b166e9dfd2f9ed3cae29652be9f')
on conflict (email) do nothing;

insert into days (day_number, title, description) values
  (1, 'Health data mining', 'Recall and apply core ideas for discovering useful patterns from health data.'),
  (2, 'Machine learning', 'Practice concepts around supervised and unsupervised learning, model training, and evaluation.'),
  (3, 'Deep neural network, transformer, reinforcement learning', 'Review deep neural networks, transformer models, and reinforcement learning concepts.'),
  (4, 'Regulation and ethics', 'Reflect on governance, regulation, privacy, fairness, and ethical use of AI in health data analysis.')
on conflict (day_number) do nothing;

insert into users (user_id, name)
values ('STUDENT002', 'Demo Student')
on conflict (user_id) do nothing;

insert into participant_day_access (user_id, day_id, access_code)
select u.id, d.id, u.user_id || '-DAY' || d.day_number
from users u
cross join days d
where u.user_id = 'STUDENT002'
on conflict (user_id, day_id) do nothing;

insert into questions (day_id, question_order, question_type, question_text, correct_answer, expected_word_count, explanation)
select d.id, 1, 'short_text', 'What process is used to discover useful patterns in large health datasets?', 'Data mining', 2, 'Data mining is used to discover patterns, relationships, and useful signals in large datasets.'
from days d
where d.day_number = 1
  and not exists (select 1 from questions q where q.day_id = d.id and q.question_order = 1);

insert into questions (day_id, question_order, question_type, question_text, explanation)
select d.id, 2, 'multiple_response', 'Which of the following are common tasks in health data mining?', 'Health data mining can include pattern discovery, clustering, association analysis, and anomaly detection.'
from days d
where d.day_number = 1
  and not exists (select 1 from questions q where q.day_id = d.id and q.question_order = 2);

insert into question_options (question_id, option_text, is_correct)
select q.id, option_text, is_correct
from questions q
join days d on d.id = q.day_id
cross join (
  values
    ('Pattern discovery', true),
    ('Clustering similar patients', true),
    ('Association analysis', true),
    ('Video game console', false),
    ('Picture editing software', false),
    ('Anomaly detection', true)
) as options(option_text, is_correct)
where d.day_number = 1
  and q.question_order = 2
  and not exists (select 1 from question_options qo where qo.question_id = q.id);

insert into questions (day_id, question_order, question_type, question_text, correct_answer, expected_word_count, explanation)
select d.id, 1, 'short_text', 'What type of machine learning uses labelled examples?', 'Supervised learning', 2, 'Supervised learning uses labelled data to train models that predict labels or outcomes.'
from days d
where d.day_number = 2
  and not exists (select 1 from questions q where q.day_id = d.id and q.question_order = 1);
